
steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', '.']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'run',
      'deploy',
      'backend-service',
      '--image',
      'gcr.io/$PROJECT_ID/backend',
      '--region',
      'us-central1',
      '--platform',
      'managed',
      '--allow-unauthenticated',
      '--port',
      '5000'
    ]
